import uuid from 'uuid/v1';

export default [
  {
    id: uuid(),
    company_name: 'AAA Company Pte Ltd',
    slug: 'ekaterina-tankova',
    email: 'ace@acesecurity.com.sg',
    avatar: '/images/avatars/avatar_2.png',
    spent: '500.00',
    currency: '$',
    type: 'Agency',
    projects: '1',
    rating: 5,
    date_added: '12 Sep 2019',
    location: 'West Virginia, USA',
    contact_number: '+65 6500 6800',
    label: 'Security Services',
    verified: true,
  },
  {
    id: uuid(),
    company_name: 'Best Cleaning Pte Ltd',
    slug: 'cao-yu',
    email: 'best@bestcleaning.com.sg',
    avatar: '/images/avatars/avatar_3.png',
    spent: '300.00',
    type: 'Freelancer',
    currency: '$',
    projects: '3',
    rating: 4.3,
    date_added: '1 Oct 2019',
    verified: true,
    contact_number: '+65 6778 6887',
    label: 'Cleaning Services',
    location: 'Bristow',
  },
  {
    id: uuid(),
    company_name: 'Crystal Clear Pte Ltd',
    slug: 'alexa-richardson',
    email: 'crystal@clear.com.sg',
    avatar: '/images/avatars/avatar_4.png',
    spent: '2,600.00',
    type: 'Enterprise',
    currency: '$',
    projects: '0',
    rating: 4.5,
    date_added: '1 Jan 2019',
    verified: true,
    contact_number: '+65 6388 9888 ',
    label: 'Cleaning Services',
    location: 'Georgia, USA',
  },
  {
    id: uuid(),
    company_name: 'Heng Huat Pte LTd',
    slug: 'anje-keizer',
    email: 'contact@henghuat.com.sg',
    avatar: '/images/avatars/avatar_5.png',
    spent: '5,600.00',
    type: 'Enterprise',
    currency: '$',
    projects: '6',
    rating: 4,
    date_added: '12 Sep 2019',
    verified: true,
    contact_number: '+65 6738 9888',
    label: 'General Contractors',
    location: 'Ohio, USA',
  },
  {
    id: uuid(),
    company_name: 'King Services',
    slug: 'clarke-gillebert',
    email: 'enquiry@kingservices.com.sg',
    avatar: '/images/avatars/avatar_6.png',
    spent: '500.00',
    type: 'Agency',
    currency: '$',
    projects: '1',
    rating: 3.5,
    date_added: '8 Sep 2019',
    verified: true,
    contact_number: '+65 6577 8738',
    label: 'Pest Control',
    location: 'Texas, USA',
  },
  {
    id: uuid(),
    company_name: 'MP Pte Ltd',
    slug: 'adam-denisov',
    email: 'info@mp.com.sg',
    avatar: '/images/avatars/avatar_7.png',
    spent: '5,230.00',
    type: 'Agency',
    currency: '$',
    projects: '0',
    rating: 3,
    date_added: '18 Oct 2019',
    verified: true,
    contact_number: '+65 8377 1324',
    label: 'Electrical Services',
    location: 'California, USA',
  },
  {
    id: uuid(),
    company_name: 'Pest Control Pte Ltd',
    slug: 'ava-gregoraci',
    email: 'pest@pestcontrol.com.sg',
    avatar: '/images/avatars/avatar_8.png',
    spent: '300.00',
    type: 'Freelancer',
    currency: '$',
    projects: '0',
    rating: 4,
    date_added: '1 Jan 2019',
    verified: true,
    contact_number: '+65 6700 4999',
    label: 'Pest Control',
    location: 'California, USA',
  },
  {
    id: uuid(),
    company_name: 'Really Pte Ltd',
    slug: 'emilee-simchenko',
    email: 'info@really.sg',
    avatar: '/images/avatars/avatar_9.png',
    spent: '100.00',
    type: 'Agency',
    currency: '$',
    projects: '4',
    rating: 4.5,
    date_added: '1 Aug 2019',
    verified: true,
    contact_number: '+65 6577 5774',
    label: 'General Contrator',
    location: 'Nevada, USA',
  },
  {
    id: uuid(),
    company_name: 'Xtra Best Pte Ltd',
    slug: 'kwak-seong-min',
    email: 'xtra@xtra.com.sg',
    avatar: '/images/avatars/avatar_10.png',
    spent: '1,000.00',
    type: 'Freelancer',
    currency: '$',
    projects: '2',
    rating: 5,
    date_added: '1 Oct 2019',
    verified: true,
    contact_number: '+65 6709 1499',
    label: 'Security Services',
    location: 'Michigan, USA',
  },
  {
    id: uuid(),
    company_name: 'Shen Yang China Company',
    slug: 'shen-zhi',
    email: 'Shen@shenyang.com.cn',
    avatar: '/images/avatars/avatar_11.png',
    spent: '2,300.00',
    type: 'Agency',
    currency: '$',
    projects: '0',
    rating: 3.9,
    date_added: '2 Aug 2019',
    verified: true,
    contact_number: '+65 6477 4349',
    label: 'Cleaning Services',
    location: 'Utah, USA',
  },
  {
    id: uuid(),
    company_name: 'Z Company',
    slug: 'merrile-burgett',
    email: 'z@z.com',
    avatar: '/images/avatars/avatar_12.png',
    spent: '200.00',
    type: 'Enterprise',
    currency: '$',
    projects: '7',
    rating: 4.2,
    location: 'Utah, USA',
    verified: true,
    contact_number: '+65 6577 1274',
    label: 'Contactor',
    date_added: '1 Aug 2019',
  },
];
